name: AKS Login (wemogy)
author: wemogy
description: Logs in to an AKS cluster
branding:
  icon: "log-in"
  color: "blue"

inputs:
  name:
    required: true
    description: "The name of the AKS cluster"
  resource-group:
    description: "The Azure Resource Group of the AKS cluster"
    required: false
  client-id:
    description: "The Azure Service Pricipal Client ID"
    required: true
  client-secret:
    description: "The Azure Service Pricipal Secret"
    required: true
  subscription-id:
    description: "The Azure Subscription of the cluster"
    required: true
  tenant-id:
    description: "The Azure Service Pricipal Tenant ID"
    required: true
  admin:
    description: "Use the admin login (for AAD enabled clusters)"
    required: true
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Azure Login
      shell: bash
      run: |
        az login \
          --service-principal \
          --username ${{ inputs.client-id }} \
          --password ${{ inputs.client-secret }} \
          --tenant ${{ inputs.tenant-id }}

    - name: Kubernetes Login
      if: inputs.admin
      shell: bash
      run: |
        if [[ "${{ inputs.admin }}" == "true" ]]; then
          az aks get-credentials \
            --name ${{ inputs.name }} \
            --resource-group ${{ inputs.resource-group }} \
            --subscription ${{ inputs.subscription-id }} \
            --admin
        else
          az aks get-credentials \
            --name ${{ inputs.name }} \
            --resource-group ${{ inputs.resource-group }} \
            --subscription ${{ inputs.subscription-id }} \
        fi
